config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Devise routes for users
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # Routes for users
  resources :users, only: [:show, :update, :destroy]  

  # Defines the root path route ("/")
  root 'posts#index'

  # Routes for posts
  resources :posts do 
    # Routes for nested routes for likes and comments
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  # Routes for likes
  resources :likes, only: [:create, :destroy]

  # Routes for comments
  resources :comments, only: [:create, :destroy]

  # Routes for friendships
  resources :friendships, only: [:create, :update, :index] do
    member do
      patch :approve
      delete :decline
    end
  end

  # Routes for notifications
  resources :notifications, only: [:index] do
    member do
      post :dismiss
    end
  end

  # Routes for photos
  resources :photos do
    resources :likes, only: [:create]
    resources :comments, only: [:create]
  end

  # Routes for static pages
  get 'market_place', to: 'pages#market_place'
  get 'messenger', to: 'pages#messenger'
  get 'memories', to: 'pages#memories'
  get 'bookmarks', to: 'pages#bookmarks'
  get 'groups', to: 'pages#groups'
  get 'videos', to: 'pages#videos'
end

app/models/notification.rb
# frozen_string_literal: true

# Notifications for users
class Notification < ApplicationRecord
  # associations, validations, etc.
  belongs_to :user

  # Set default value for 'read' attribute
  after_initialize :set_defaults, unless: :persisted?

  private

  def set_defaults
    self.read ||= false
  end
end

app/controllers/notifications_controller.rb
# frozen_string_literal: true

# Notifications controller
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.notifications.where(read: false)
    Turbo::StreamsChannel.broadcast_refresh_to "notification_event"
  end

  def dismiss
    notification = current_user.notifications.find(params[:id])
    if notification.update(read: true)
      Turbo::StreamsChannel.broadcast_refresh_to "notification_event"
      redirect_to friendships_path, notice: 'Notification dismissed'
    else
      redirect_to root_path, alert: 'Unable to dismiss notification.'
    end
  end
end

app/views/notifications/_icon.html.erb
<!-- app/views/notifications/_icon.html.erb -->
<%= turbo_stream_from "notification_event" %>
<% if current_user.notifications.where(read: false).exists? %>
    <% current_user.notifications.where(read: false).each do |notification_false| %>
      <%= button_to dismiss_notification_path(notification_false) do %>
          <svg class="mx-auto h-6 w-auto fill-red-500" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
          </svg>
      <% end %>
   <% end %>
  <% else %>
    <button type="button" class="rounded-full bg-white p-1 text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
      <span class="sr-only">View notifications</span>
      <svg class="mx-auto h-6 w-auto" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
      </svg>
    </button>
<% end %>