config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Devise routes for users
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # Routes for users
  resources :users, only: [:show, :update, :destroy]  

  # Defines the root path route ("/")
  root 'posts#index'

  # Routes for posts
  resources :posts do 
    # Routes for nested routes for likes and comments
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  # Routes for likes
  resources :likes, only: [:create, :destroy]

  # Routes for comments
  resources :comments, only: [:create, :destroy]

  # Routes for friendships
  resources :friendships, only: [:create, :update, :index] do
    member do
      patch :approve
      delete :decline
    end
  end

  # Routes for notifications
  resources :notifications, only: [:index] do
    member do
      post :dismiss
    end
  end

  # Routes for photos
  resources :photos do
    resources :likes, only: [:create]
    resources :comments, only: [:create]
  end

  # Routes for static pages
  get 'market_place', to: 'pages#market_place'
  get 'messenger', to: 'pages#messenger'
  get 'memories', to: 'pages#memories'
  get 'bookmarks', to: 'pages#bookmarks'
  get 'groups', to: 'pages#groups'
  get 'videos', to: 'pages#videos'
end

app/views/shared/_bookmarks_icon.html.erb
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512" 
  class="mx-auto h-6 w-auto rounded-md fill-sky-700 lg:h-6"><!--! Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2023 Fonticons, Inc.--><path d="M0 48v439.7C0 501.1 10.9 512 24.3 512c5 0 9.9-1.5 14-4.4L192 400l153.7 107.6c4.1 2.9 9 4.4 14 4.4 13.4 0 24.3-10.9 24.3-24.3V48c0-26.5-21.5-48-48-48H48C21.5 0 0 21.5 0 48z"/>
</svg>

app/views/shared/_camera_icon.html.erb
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" 
  class="mx-auto h-6 p-1 w-auto fill-gray-900 lg:h-8">
<!--! Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2023 Fonticons, Inc.-->
  <path d="M220.6 121.2 271.1 96H448v96H333.2c-21.9-15.1-48.5-24-77.2-24s-55.2 8.9-77.2 24H64v-64h128c9.9 0 19.7-2.3 28.6-6.8zM0 128v288c0 35.3 28.7 64 64 64h384c35.3 0 64-28.7 64-64V96c0-35.3-28.7-64-64-64H271.1c-9.9 0-19.7 2.3-28.6 6.8L192 64h-32V48c0-8.8-7.2-16-16-16H80c-8.8 0-16 7.2-16 16v16C28.7 64 0 92.7 0 128zm168 176a88 88 0 1 1 176 0 88 88 0 1 1-176 0z"/>
</svg>

app/views/shared/_close_x_icon.html.erb
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="mx-auto w-auto h-4">
<!--! Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2023 Fonticons, Inc.-->
  <path d="M256 48a208 208 0 1 1 0 416 208 208 0 1 1 0-416zm0 464a256 256 0 1 0 0-512 256 256 0 1 0 0 512zm-81-337c-9.4 9.4-9.4 24.6 0 33.9l47 47-47 47c-9.4 9.4-9.4 24.6 0 33.9s24.6 9.4 33.9 0l47-47 47 47c9.4 9.4 24.6 9.4 33.9 0s9.4-24.6 0-33.9l-47-47 47-47c9.4-9.4 9.4-24.6 0-33.9s-24.6-9.4-33.9 0l-47 47-47-47c-9.4-9.4-24.6-9.4-33.9 0z"/>
</svg>

app/views/shared/_friends_icon.html.erb
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" 
  class="<%= svg_class %> mx-auto h-6 w-auto rounded-md fill-gray-700 lg:h-8">
  <path class="primary" d="M12 13a3 3 0 0 1 3-3h4a3 3 0 0 1 3 3v3a1 1 0 0 1-1 1h-8a1 1 0 0 1-1-1 1 1 0 0 1-1 1H3a1 1 0 0 1-1-1v-3a3 3 0 0 1 3-3h4a3 3 0 0 1 3 3zM7 9a3 3 0 1 1 0-6 3 3 0 0 1 0 6zm10 0a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/><path class="secondary" d="M12 13a3 3 0 1 1 0-6 3 3 0 0 1 0 6zm-3 1h6a3 3 0 0 1 3 3v3a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1v-3a3 3 0 0 1 3-3z"/>
</svg>

app/views/shared/_groups_icon.html.erb
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512" 
  class="mx-auto h-6 w-auto rounded-md fill-sky-700 lg:h-6"><!--! Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2023 Fonticons, Inc.--><path d="M72 88a56 56 0 1 1 112 0 56 56 0 1 1-112 0zm-8 157.7c-10 11.2-16 26.1-16 42.3s6 31.1 16 42.3v-84.6zm144.4-49.3C178.7 222.7 160 261.2 160 304c0 34.3 12 65.8 32 90.5V416c0 17.7-14.3 32-32 32H96c-17.7 0-32-14.3-32-32v-26.8C26.2 371.2 0 332.7 0 288c0-61.9 50.1-112 112-112h32c24 0 46.2 7.5 64.4 20.3zM448 416v-21.5c20-24.7 32-56.2 32-90.5 0-42.8-18.7-81.3-48.4-107.7C449.8 183.5 472 176 496 176h32c61.9 0 112 50.1 112 112 0 44.7-26.2 83.2-64 101.2V416c0 17.7-14.3 32-32 32h-64c-17.7 0-32-14.3-32-32zm8-328a56 56 0 1 1 112 0 56 56 0 1 1-112 0zm120 157.7v84.7c10-11.3 16-26.1 16-42.3s-6-31.1-16-42.3zM320 32a64 64 0 1 1 0 128 64 64 0 1 1 0-128zm-80 272c0 16.2 6 31 16 42.3v-84.6c-10 11.3-16 26.1-16 42.3zm144-42.3v84.7c10-11.3 16-26.1 16-42.3s-6-31.1-16-42.3zm64 42.3c0 44.7-26.2 83.2-64 101.2V448c0 17.7-14.3 32-32 32h-64c-17.7 0-32-14.3-32-32v-42.8c-37.8-18-64-56.5-64-101.2 0-61.9 50.1-112 112-112h32c61.9 0 112 50.1 112 112z"/>
</svg>

app/views/shared/_marketplace_icon.html.erb
 <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" 
    class="<%= svg_class %> mx-auto h-6 w-auto rounded-md fill-gray-700 lg:h-8">
    <path d="m547.6 103.8-57.3-90.7C485.2 5 476.1 0 466.4 0H109.6c-9.7 0-18.8 5-23.9 13.1l-57.4 90.7c-29.6 46.8-3.4 111.9 51.9 119.4 4 .5 8.1.8 12.1.8 26.1 0 49.3-11.4 65.2-29 15.9 17.6 39.1 29 65.2 29s49.3-11.4 65.2-29c15.9 17.6 39.1 29 65.2 29 26.2 0 49.3-11.4 65.2-29 16 17.6 39.1 29 65.2 29 4.1 0 8.1-.3 12.1-.8 55.5-7.4 81.8-72.5 52.1-119.4zm-47.9 151.1h-.1c-5.3.7-10.7 1.1-16.2 1.1-12.4 0-24.3-1.9-35.4-5.3V384H128V250.6c-11.2 3.5-23.2 5.4-35.6 5.4-5.5 0-11-.4-16.3-1.1H76c-4.1-.6-8.1-1.3-12-2.3V448c0 35.3 28.7 64 64 64h320c35.3 0 64-28.7 64-64V252.6c-4 1-8 1.8-12.3 2.3z"/>
  </svg>

app/views/shared/_memories_icon.html.erb
<svg xmlns="http://www.w3.org/2000/svg" 
  class="mx-auto h-6 w-auto rounded-md fill-sky-700 lg:h-6" 
  viewBox="0 0 512 512" stroke-width="1.5" stroke="currentColor" aria-hidden="true"><!--! Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2023 Fonticons, Inc.--><path d="M75 75 41 41C25.9 25.9 0 36.6 0 57.9V168c0 13.3 10.7 24 24 24h110.1c21.4 0 32.1-25.9 17-41l-30.8-30.8C155 85.5 203 64 256 64c106 0 192 86 192 192s-86 192-192 192c-40.8 0-78.6-12.7-109.7-34.4-14.5-10.1-34.4-6.6-44.6 7.9s-6.6 34.4 7.9 44.6C151.2 495 201.7 512 256 512c141.4 0 256-114.6 256-256S397.4 0 256 0C185.3 0 121.3 28.7 75 75zm181 53c-13.3 0-24 10.7-24 24v104c0 6.4 2.5 12.5 7 17l72 72c9.4 9.4 24.6 9.4 33.9 0s9.4-24.6 0-33.9l-65-65V152c0-13.3-10.7-24-24-24z"/>
</svg>

app/views/shared/_messenger_icon.html.erb
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" 
  class="<%= svg_class %> mx-auto h-6 w-auto rounded-md fill-gray-400 stroke-1 lg:h-8">
<!--! Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2023 Fonticons, Inc.-->
  <path d="M160 368c26.5 0 48 21.5 48 48v16l72.5-54.4c8.3-6.2 18.4-9.6 28.8-9.6H448c8.8 0 16-7.2 16-16V64c0-8.8-7.2-16-16-16H64c-8.8 0-16 7.2-16 16v288c0 8.8 7.2 16 16 16h96zm48 124-.2.2-5.1 3.8-17.1 12.8c-4.8 3.6-11.3 4.2-16.8 1.5s-8.8-8.2-8.8-14.3v-80H64c-35.3 0-64-28.7-64-64V64C0 28.7 28.7 0 64 0h384c35.3 0 64 28.7 64 64v288c0 35.3-28.7 64-64 64H309.3L208 492z"/>
</svg>

app/views/shared/_navbar.html.erb
<%= turbo_stream_from "notification_event" %>
<!-- Navbar -->
<nav data-controller="menu" class="bg-white shadow fixed top-0 w-full mb-5">
  <!-- Container -->
  <div class="mx-auto max-w-9xl px-2 sm:px-4 lg:px-8">
    <!-- Container -->
    <div class="grid grid-cols-5 h-16 justify-between lg:grid-cols-6" data-controller="search">
      <!-- Logo, Search and Navigation -->
      <div class="col-start-1 col-end-1 grid grid-cols-3 px-2 lg:grid-cols-4 lg:px-0 lg:col-end-3"  data-search-target="searchParent">
        <!-- Logo -->
        <div class="self-center grid justify-items-end col-start-1 col-end-3 lg:col-end-1" data-search-target="searchLogo">
          <a href="/">
            <%= render "devise/shared/logo_small" %>
          </a> 
        </div>
        <!-- Search box -->
        <div class="self-center justify-center px-2 lg:justify-end lg:col-start-2 lg:col-end-4" data-search-target="searchField">
          <div class="w-full max-w-lg lg:max-w-xs">
            <label for="search" class="sr-only">Search</label>
            <div class="grid grid-cols-6" >
              <div class="self-center cols-start-1 col-end-1 w-8 inset-y-0 left-0 items-center">
                <button data-action="click->search#toggleSearch" class="self-center">
                  <%= render partial: 'shared/search_icon' %>
                </button>
              </div>
              <input id="search" name="search" class="hidden col-start-1 col-end-6 block w-full rounded-md border-0 
                bg-gray-100 py-1.5 pr-3 text-gray-900 ring-1 ring-inset ring-gray-300 
                placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-sky-600 
                sm:text-sm sm:leading-6 lg:flex" placeholder="Search" type="search"
                data-search-target="searchBox">
            </div>
          </div>
        </div> 
      </div>
      <!-- Desktop: Navigation Home, Friends, Messenger, MarketPlace -->
      <div class="hidden self-center items-center mx-auto h-12 w-auto lg:flex 
                  lg:space-x-8 grid grid-cols-4 col-start-3 col-end-5" data-controller="navbar">
        <!-- Home -->
        <a href="/" class=" px-1 pt-1 col-start-1 col-end-1 w-16 border-b-2 w-16 border-transparent
                             text-sm font-medium text-gray-500 hover:bg-gray-100 hover:rounded-lg"
                    data-navbar-target="link">
        <%= render partial: 'shared/home_icon', locals: { svg_class: "svg-icon" } %>
        </a>
        <!-- Friends -->
        <a href="<%= friendships_path %>" class="px-1 pt-1 col-start-2 col-end-2
                                                 border-b-2 w-16 border-transparent 
                                                 text-sm font-medium text-gray-500 
                                                 hover:bg-gray-100 hover:rounded-lg"
                                          data-navbar-target="link">
          <%= render partial: 'shared/friends_icon', locals: { svg_class: "svg-icon" } %>
        </a>
        <!-- Messenger -->
        <a href="<%= messenger_path %>" class="pt-1 pb-1 col-start-3 col-end-3 
                                              border-b-2 w-16 border-transparent
                                              text-sm font-medium text-gray-500 
                                              hover:bg-gray-100 hover:rounded-lg" 
                    data-navbar-target="link">
          <%= render partial: 'shared/messenger_icon', locals: { svg_class: "svg-icon" } %>
        </a>
        <!-- Market Place -->
        <a href="<%= market_place_path %>" class="pt-1 pb-1 col-start-4 col-end-4 
                                                border-b-2 w-16 border-transparent 
                                                text-sm font-medium text-gray-500 
                                                hover:bg-gray-100 hover:rounded-lg" 
                    data-navbar-target="link">
          <%= render partial: 'shared/marketplace_icon', locals: { svg_class: "svg-icon" } %> 
        </a>
      </div>
      
      <!-- Mobile: Messenger, notifications and gravatar icons -->
      <div class="col-start-3 col-end-5 self-center lg:hidden" data-menu-target="icons">
        <div class="grid grid-cols-3 items-center" >
          <!-- Messenger icon -->
          <div class="col-start-1 col-end-1 sm:hidden" >
            <a href="<%= messenger_path %>">
              <%= render partial: "shared/messenger_icon", locals: { svg_class: "svg-icon" } %>
            </a>
          </div>
          <!-- Notifications icon -->
          <div class="grid grid-cols-1 col-start-2 col-end-2 self-center sm:hidden">
            <%= render partial: "notifications/icon", 
              locals: { notifications: current_user.notifications.where(read: false) } %>
          </div>
          <!-- Gravatar -->
          <div class="col-start-3 col-end-3 sm:hidden">
            <% if current_user.profile_picture.attached? %>
              <%= image_tag current_user.profile_picture, alt: "User avatar", 
                class: "mx-auto h-8 w-auto rounded-full" %>
            <% else %>
              <%= image_tag gravatar_for(current_user), alt: current_user.username, 
                class: "mx-auto h-8 w-auto rounded-full" %>
            <% end %>
          </div>
        </div>
      </div>
      <!-- Mobile: Menu button -->
      <div class="col-start-5 col-end-5 self-center grid grid-cols-1 items-center lg:hidden">  
        <button type="button" 
                data-action="click->menu#toggle" 
                class="relative rounded-md p-2 text-gray-400 hover:bg-gray-100 
                  hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset 
                  focus:ring-sky-500" 
                aria-controls="mobile-menu" 
                aria-expanded="false">
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open main menu</span>
          <!-- Icon when menu is closed. -->        
          <%= render partial: "shared/menu_closed_icon" %>
          <!-- Icon when menu is open. -->
          <%= render partial: "shared/menu_open_icon" %>
        </button>
      </div>
      <!-- Desktop: Profile, Notifications -->
      <div class="hidden col-start-6 col-end-6 grid grid-cols-3 self-center lg:flex 
                  lg:ml-4 lg:items-center lg:grid lg:grid-cols-4">
        <!-- Notifications icon -->
        <div id="notifications">
          <%= render partial: "notifications/icon", 
            locals: { notifications: current_user.notifications.where(read: false) }
          %>
        </div>
        <!-- User name-->
        <div class="text-xs text-sky-700 lg:text-xs lg:col-start-2 lg:col-end-3"><%= current_user.username %></div>
        <!-- Desktop: Profile dropdown -->
        <div data-controller="menu" class="relative p-2">
          <div class="mx-auto h-8 w-auto">
            <button type="button" data-action="click->menu#toggle" 
                    class="relative rounded-full bg-white text-sm 
                          focus:outline-none focus:ring-2 focus:ring-sky-500 
                          focus:ring-offset-2" id="user-menu-button" aria-expanded="false" 
                          aria-haspopup="true">
              <span class="absolute -inset-1.5"></span>
              <span class="sr-only">Open user menu</span>
              <!-- Users Gravatar-->
              <%= image_tag gravatar_for(current_user), alt: current_user.username, 
                                                        class:"h-8 w-8 rounded-full"
              %>
            </button>
          </div>
          
          <!--
            Dropdown menu, show/hide based on menu state.

            Entering: "transition ease-out duration-100"
              From: "transform opacity-0 scale-95"
              To: "transform opacity-100 scale-100"
            Leaving: "transition ease-in duration-75"
              From: "transform opacity-100 scale-100"
              To: "transform opacity-0 scale-95"
          -->
          <div data-menu-target="toggleable" class="hidden absolute right-0 z-10 
                                                    mt-2 w-48 origin-top-right 
                                                    rounded-md bg-white py-1 
                                                    shadow-lg ring-1 ring-black 
                                                    ring-opacity-5 focus:outline-none" 
                                                    role="menu" aria-orientation="vertical" 
                                                    aria-labelledby="user-menu-button" tabindex="-1">
            <!-- Active: "bg-gray-100", Not Active: "" -->
            <a href="<%= user_path(current_user) %>" class="block px-4 py-2 text-sm text-gray-700" 
                        role="menuitem" .
                        tabindex="-1" 
                        id="user-menu-item-0">Your Profile</a>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700" 
                        role="menuitem" 
                        tabindex="-1" 
                        id="user-menu-item-1">Settings</a>
            <%= form_tag destroy_user_session_path, method: :delete do %>
              <%= button_to "Sign Out", destroy_user_session_path, method: :delete, 
                class: "block px-4 py-2 text-sm text-gray-700" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="hidden lg:hidden" id="mobile-menu" data-menu-target="toggleable">
    <!-- Mobile: Navigation -->
    <div class="space-y-1 pb-3 pt-2" data-controller="navbar">
      <!-- Home -->
      <a href="/" class="grid grid-cols-8 col-start-1 items-center text-center 
                         block border-l-4 border-transparent py-2 pl-1 pr-4 
                         text-base font-medium text-gray-600 focus:bg-gray-200 
                         active:bg-gray-200"
                      data-navbar-target="link">
        <%= render partial: 'shared/home_icon', class:"col-start-2", locals: { svg_class: "svg-icon" } %>
        Home
      </a>
      <!-- Friends -->
      <a href="<%= friendships_path %>" class="grid grid-cols-8 col-start-1 
                                              items-center text-center block border-l-4 
                                              border-transparent py-2 pl-1 pr-4 
                                              text-base font-medium text-gray-600 
                                              focus:bg-gray-200 active:bg-gray-200"
        data-navbar-target="link">
        <%= render partial: 'shared/friends_icon', class: "col-start-1 col-end-1", locals: { svg_class: "svg-icon" } %>
        Friends
      </a>
      <!-- Messenger -->
      <a href="<%= messenger_path %>" class="grid grid-cols-8 col-start-1 
                                            items-center text-center block border-l-4 
                                            border-transparent py-2 pl-1 pr-4 
                                            text-base font-medium text-gray-600 
                                            focus:bg-gray-200 active:bg-gray-200" 
        data-navbar-target="link">
        <%= render partial: 'shared/messenger_icon', class: "col-start-1 col-end-1", locals: { svg_class: "svg-icon" } %>
        Messenger
      </a>
      <!-- Market Place -->
      <a href="<%= market_place_path %>" class="grid grid-cols-8 col-start-2 col-end-4
                                                items-center text-center block border-l-4 
                                                border-transparent py-2 pl-1 pr-4 
                                                text-base font-medium text-gray-600 
                                                focus:bg-gray-200 active:bg-gray-200" 
        data-navbar-target="link">
        <%= render partial: 'shared/marketplace_icon', class: "col-start-1 col-end-1", 
          locals: { svg_class: "svg-icon" } 
        %>  
        <div class="col-start-2 col-end-5 text-left">Market Place</div>
      </a>
      <!-- Profile -->
      <a href="<%= user_path(current_user) %>" class="grid grid-cols-8 col-start-2 col-end-4
                                                      items-center text-center block 
                                                      border-l-4 border-transparent py-2 pl-1 pr-4 
                                                      text-base font-medium text-gray-600 
                                                      focus:bg-gray-200 active:bg-gray-200" 
        data-navbar-target="link">
        <%= render partial: 'shared/profile_icon', class: "col-start-1 col-end-1", 
          locals: { svg_class: "svg-icon" } 
        %> 
        Profile
      </a>
    </div>
  </div>
</nav>

app/views/shared/_paperclip_icon.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
  <path fill-rule="evenodd" d="M15.621 4.379a3 3 0 00-4.242 0l-7 7a3 3 0 004.241 4.243h.001l.497-.5a.75.75 0 011.064 1.057l-.498.501-.002.002a4.5 4.5 0 01-6.364-6.364l7-7a4.5 4.5 0 016.368 6.36l-3.455 3.553A2.625 2.625 0 119.52 9.52l3.45-3.451a.75.75 0 111.061 1.06l-3.45 3.451a1.125 1.125 0 001.587 1.595l3.454-3.553a3 3 0 000-4.242z" clip-rule="evenodd" />
</svg>

app/views/shared/_paperplane_icon.html.erb
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512", class= "mx-auto h-4 w-auto rounded-md fill-sky-700 lg:h-6">>
<!--! Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2023 Fonticons, Inc.-->
  <path d="M16.1 260.2c-22.6 12.9-20.5 47.3 3.6 57.3L160 376v103.3c0 18.1 14.6 32.7 32.7 32.7 9.7 0 18.9-4.3 25.1-11.8l62-74.3 123.9 51.6c18.9 7.9 40.8-4.5 43.9-24.7l64-416c1.9-12.1-3.4-24.3-13.5-31.2s-23.3-7.5-34-1.4l-448 256zm52.1 25.5L409.7 90.6 190.1 336l1.2 1-123.1-51.3zm335.1 139.7-166.6-69.5 214.1-239.3-47.5 308.8z"/>
</svg>

app/views/shared/_pen_icon.html.erb
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"
  class="mx-auto h-6 p-1 w-auto fill-gray-900 lg:h-8">
<!--! Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2023 Fonticons, Inc.-->
  <path d="m362.7 19.3-48.4 48.4 130 130 48.4-48.4c25-25 25-65.5 0-90.5l-39.4-39.5c-25-25-65.5-25-90.5 0zm-71 71L58.6 323.5c-10.4 10.4-18 23.3-22.2 37.4L1 481.2c-2.5 8.5-.2 17.6 6 23.8s15.3 8.5 23.7 6.1L151 475.7c14.1-4.2 27-11.8 37.4-22.2l233.3-233.2-130-130z"/>
</svg>