config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Devise routes for users
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # Routes for users
  resources :users, only: [:show, :update, :destroy]  

  # Defines the root path route ("/")
  root 'posts#index'

  # Routes for posts
  resources :posts do 
    # Routes for nested routes for likes and comments
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  # Routes for likes
  resources :likes, only: [:create, :destroy]

  # Routes for comments
  resources :comments, only: [:create, :destroy]

  # Routes for friendships
  resources :friendships, only: [:create, :update, :index] do
    member do
      patch :approve
      delete :decline
    end
  end

  # Routes for notifications
  resources :notifications, only: [:index] do
    member do
      post :dismiss
    end
  end

  # Routes for photos
  resources :photos do
    resources :likes, only: [:create]
    resources :comments, only: [:create]
  end

  # Routes for static pages
  get 'market_place', to: 'pages#market_place'
  get 'messenger', to: 'pages#messenger'
  get 'memories', to: 'pages#memories'
  get 'bookmarks', to: 'pages#bookmarks'
  get 'groups', to: 'pages#groups'
  get 'videos', to: 'pages#videos'
end

app/models/friendship.rb
# frozen_string_literal: true

# Friendship relationships to users
class Friendship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/controllers/friendships_controller.rb
# frozen_string_literal: true

# app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = current_user.following_relationships.build(followed_id: params[:followed_id], status: 'pending')
    if @friendship.save
      # Redirect or respond as necessary
      create_notification_for(@friendship)
      Turbo::StreamsChannel.broadcast_refresh_to "friend_request"
      Turbo::StreamsChannel.broadcast_refresh_to "notification_event"
      redirect_to friendships_path, notice: 'Friend request sent'
    else
      # Handle errors
      flash[:alert] = 'Unable to send friend request.'
      redirect_back(fallback_location: root_path)
    end
  end

  def update
    @friendship = Friendship.find(params[:id])
    if @friendship.update(status: 'approved')
      # Redirect or respond as necessary
    else
      # Handle errors
      flash[:alert] = 'Unable to update friend request.'
      redirect_back(fallback_location: root_path)
    end
  end

  def index
    @users = User.where.not(id: current_user.id)

    # retrieve the users who have sent a follow request to the current user and are waiting for approval
    @pending_followers = current_user.follower_relationships.includes(:follower).where(status: 'pending')

    # retrieve the users whom the current user has sent a follow request to and are waiting for their approval
    @pending_following = current_user.following_relationships.includes(:followed).where(status: 'pending')

    # retrieve the users who are approved followers of the current user
    @approved_followers  = current_user.follower_relationships.includes(:follower).where(status: 'approved')
  end

  def approve
    puts params.inspect
    friendship = Friendship.find(params[:id])
    if friendship.update(status: 'approved')
      redirect_to friendships_path, notice: 'Friend request approved'
    else
      # Handle errors
      flash[:alert] = 'Unable to approve friend request.'
      redirect_back(fallback_location: root_path)
    end
  end

  def decline
    puts params.inspect
    friendship = Friendship.find(params[:id])
    if friendship.destroy
      # Redirect if friendship is declined
      redirect_to friendships_path, notice: 'Friend request declined'
    else
      # Handle errors
      flash[:alert] = 'Unable to decline friend request.'
      redirect_back(fallback_location: root_path)
    end
  end

  def create_notification_for(friendship)
    Notification.create(
      user_id: friendship.followed_id
    )
  end
end

app/views/friendships/_confirmed.html.erb
<%# People who are your friends %>
<h2 class="container mx-auto px-5 pb-2 pt-5 justify-center text-center font-semibold w-3/4">Your Friends</h2>
<ul class="lg:pt-5">
  <li>
      <% @approved_followers.each do |friend|%>
        <div class="container mx-auto px-5 justify-center ">
          <!-- Friend Container -->
          <div class="border-b border-gray-200 bg-white px-4 py-5 sm:px-6">
              <div class="grid grid-cols-4">
                <!-- Friend name -->
                <%= image_tag gravatar_for(friend.follower), alt: friend.follower, 
                    class: "mx-auto h-14 w-auto rounded-full col-start-1 col-end-1 
                            self-center border-gray-300 border-2" %>
                <h3 class="col-start-2 col-end-3 text-base 
                           leading-6 text-gray-700 self-center"><%= friend.follower.username %></h3>
                <!-- Remove friend button -->
                <div class="col-start-4 col-end-4 self-center">
                <%= button_to 'Remove', decline_friendship_path(friend), :method => :delete,
                class: "rounded-lg bg-gray-300 px-2.5 py-2 text-xs font-semibold
                            text-gray-800 shadow-sm hover:bg-gray-500 focus-visible:outline 
                            focus-visible:outline-2 focus-visible:outline-offset-2 
                            focus-visible:outline-gray-600" %>
                </div>
              </div>
          </div>
        </div>
      <% end %>
  </li>
</ul>

app/views/friendships/_friends_sidebar.html.erb
<!-- Sidebar -->
<div class="grid grid-rows-5 gap-y-5 overflow-y-auto bg-slate-100 ml-28 pt-5">
  <nav>
    <ul role="list" class="gap-y-5">
      <li>
        <ul role="list" class="-mx-1 space-y-1">
          <!-- Friend Requests -->
          <li class="p-2 w-60 h-14">
            <button class="rounded-md p-2 self-center w-48 text-gray-800", 
                    data-action="click->friendship#toggleSection" data-friendship-target="desktoprequestsButton" >
              <div class="grid grid-cols-6">
                <%= render partial: 'shared/friend_request_icon' , 
                    class:"col-start-1 col-end-1 justify-self-center", locals: { svg_class: "svg-icon" } %>
              <div class="col-start-3 col-end-6 text-sm font-semibold 
                          gap-x-1 self-center justify-self-start">Requests</div> 
            </button>
          </li>
          <!-- Your Friends -->
          <li class="p-2 w-60 h-14">
            <button class="rounded-md p-2 self-center w-48 text-white bg-sky-500"
                    data-action="click->friendship#toggleSection" data-friendship-target="desktopfriendsButton">
              <div class="grid grid-cols-6">
                <%= render partial: 'shared/friends_icon' , 
                    class:"col-start-1 col-end-1 self-center", locals: { svg_class: "svg-icon" } %>
                <div class="col-start-3 col-end-6 text-sm font-semibold hover:text-sky-600
                            gap-x-1 self-center justify-self-start">Friends</div> 
              </div>
            </button>
          </li>
          <!-- Friends Suggestions -->
          <li class="p-2 w-60 h-14">
            <button class="rounded-md p-2 self-center w-48 text-gray-800"
                    data-action="click->friendship#toggleSection" data-friendship-target="desktopsuggestionsButton">
              <div class="grid grid-cols-6">
                <%= render partial: 'shared/friends_suggestions',
                    
                    class:"col-start-1 col-end-1 justify-self-center",  locals: { svg_class: "svg-icon" } %>
                <span class="col-start-3 col-end-6 text-sm font-semibold 
                            gap-x-1 self-center justify-self-start">Suggestions</span>
              </div>
            </button>
          </li>
        </ul>  
      </li>    
    </ul>
  </nav>
</div>

app/views/friendships/_requests.html.erb
<%= turbo_stream_from "friend_request" %>
<%= turbo_stream_from "notification_event" %>

<%# Friend Requests %>
<h2 class="container mx-auto px-5 pb-2 pt-5 justify-center text-center font-semibold w-3/4">Friend Requests</h2>

  <% if @pending_followers.blank?%>
        <div class="container mx-auto lg:pt-5 px-5 pb-2 justify-center text-center font-semibold w-4/4">
          You have no pending friend requests</div>
  <% else %>

  <ul class="lg:pt-5">
    <li>
        <% @pending_followers.each do |request|%>
          <div class="container mx-auto px-5 justify-center ">
            <!-- Friend Container -->
            <div class="border-b border-gray-200 bg-white px-4 py-5 sm:px-6">
                <div class="grid grid-cols-4">
                  <!-- Friend name -->
                  <%= image_tag gravatar_for(request.follower), alt: request.follower, 
                      class: "mx-auto h-14 w-auto rounded-full col-start-1 col-end-1 
                              self-center border-gray-300 border-2" %>
                  <h3 class="col-start-2 col-end-3 text-base 
                            leading-6 text-gray-700 self-center"><%= request.follower.username %></h3>
                  <!-- Approve Friendship -->
                  <div class="col-start-3 col-end-4 self-center">
                  <%= button_to 'Approve', approve_friendship_path(request), :method => :patch,
                  class: "rounded-lg bg-sky-700 px-2.5 py-2 text-xs font-semibold
                              text-white shadow-sm hover:bg-gray-500 focus-visible:outline 
                              focus-visible:outline-2 focus-visible:outline-offset-2 
                              focus-visible:outline-gray-600" %>
                  </div>
                  <!-- Decline Friendship -->
                  <div class="col-start-4 col-end-4 self-center">
                  <%= button_to 'Decline', decline_friendship_path(request), :method => :delete,
                  class: "rounded-lg bg-gray-300 px-2.5 py-2 text-xs font-semibold
                              text-gray-800 shadow-sm hover:bg-gray-500 focus-visible:outline 
                              focus-visible:outline-2 focus-visible:outline-offset-2 
                              focus-visible:outline-gray-600" %>
                  </div>
                </div>
            </div>
          </div>
        <% end %>
    </li>
    <% end %>
  </ul>

  <%# Friend To Follow %>
  <h2 class="container mx-auto px-5 pb-2 justify-center text-center font-semibold w-3/4">Friends to Follow</h2>
  <% if @pending_following.nil?%>
        <p class="container mx-auto px-5 pb-2 justify-center text-center font-semibold w-3/4">No one here to follow</p>
  <% else %>
  <ul>
    <li>
        <% @pending_following.each do |request|%>
          <div class="container mx-auto px-5 justify-center ">
            <!-- Friend Container -->
            <div class="border-b border-gray-200 bg-white px-4 py-5 sm:px-6">
                <div class="grid grid-cols-4">
                  <!-- Friend name -->
                  <%= image_tag gravatar_for(request.followed), alt: request.followed, 
                      class: "mx-auto h-14 w-auto rounded-full col-start-1 col-end-1 
                              self-center border-gray-300 border-2" %>
                  <h3 class="col-start-2 col-end-3 text-base 
                            leading-6 text-gray-700 self-center"><%= request.followed.username %></h3>
                  <!-- Follow Friend -->
                  <div class="col-start-3 col-end-4 self-center">
                  <%= button_to 'Follow', approve_friendship_path(request), :method => :patch,
                  class: "rounded-lg bg-sky-700 px-2.5 py-2 text-xs font-semibold
                              text-white shadow-sm hover:bg-gray-500 focus-visible:outline 
                              focus-visible:outline-2 focus-visible:outline-offset-2 
                              focus-visible:outline-gray-600" %>
                  </div>
                </div>
            </div>
          </div>
        <% end %>
    </li>
    <% end %>
  </ul>

app/views/friendships/_suggestions.html.erb
<%# User card for suggested friends %>
<h2 class="container mx-auto px-5 pb-2 pt-5 justify-center text-center font-semibold w-3/4">People you might know</h2>
<div class="lg:min-h-screen lg:bg-slate-100 lg:flex lg:justify-center">
  <div class="bg-slate-100 lg:pt-5 lg:min-h-screen lg:bg-slate-100 lg:flex lg:justify-center">
    <ul>
      <li>
          <% @users.each.each do |user|%>
            <div class="container mx-auto px-5 justify-center ">
              <!-- Friend Container -->
              <div class="border-b border-gray-200 bg-white px-4 py-5 sm:px-6">
                  <div class="grid grid-cols-4">
                    <% unless current_user == user || current_user.following.include?(user) %>
                      <!-- Friend name -->
                      <%= image_tag gravatar_for(user), alt: user.username, 
                          class: "mx-auto h-14 w-auto rounded-full col-start-1 col-end-1 
                                  self-center border-gray-300 border-2" %>
                      <h3 class="col-start-2 col-end-3 text-base 
                                leading-6 text-gray-700 self-center"><%= user.username %></h3>
                      <!-- Suggested friends button -->
                      <div class="col-start-4 col-end-4 self-center">
                      <%= button_to 'Request Friendship', friendships_path(followed_id: user.id), :method => :post,
                        class: "rounded-lg bg-sky-700 px-2.5 py-2 text-xs font-semibold
                                    text-white shadow-sm hover:bg-gray-500 focus-visible:outline 
                                    focus-visible:outline-2 focus-visible:outline-offset-2 
                                    focus-visible:outline-gray-600" %>
                      </div>
                    <% end %>    
                  </div>
              </div>
            </div>
          <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/friendships/index.html.erb
<div class="h-screen bg-slate-100" >  
  <!-- Navbar -->
  <div class="fixed top-0 z-30 w-full">
    <%= render "shared/navbar" %>
  </div>

  <div class="pt-20 grid grid-rows-[25px, 1fr] lg:grid-cols-6 lg:gap-4 lg:pt-3 lg:pt-8 lg:h-full" 
    data-controller="friendship">
    <!-- Sidebar -->
    <div  class="hidden lg:block lg:col-span-2 lg:pt-8">
      <%= render "friendships/friends_sidebar" %>
    </div>

    <!-- Content Area: Form and Posts -->
    <div class="lg:col-span-2 px-4 py-4 overflow-auto overflow-y-scroll">

      <!-- Main content -->
      <div class="grid grid-rows-[10px, 20px]">
        
        <div class="grid grid-cols-6 gap-2 px-2.5 pb-3 ml-3">
          <!-- Mobile Buttons -->
          <!-- Your Friends -->
          <button data-action="click->friendship#toggleSection" data-friendship-target="mobilefriendsButton"
            class="col-start-1 col-end-3 rounded-full bg-sky-500 px-1.5 py-2 text-xs font-semibold
                        text-white shadow-sm lg:hover:bg-gray-500 lg:focus-visible:outline 
                        lg:focus-visible:outline-2 lg:focus-visible:outline-offset-2 
                        lg:focus-visible:outline-gray-600 lg:hidden">Your Friends</button>
          <!-- Follower Requests -->
          <button data-action="click->friendship#toggleSection" data-friendship-target="mobilerequestsButton" 
                  class="col-start-3 col-end-5 rounded-full bg-gray-300 px-1.5 py-2 text-xs font-semibold
                        text-gray-800 shadow-sm lg:hover:bg-gray-500 lg:focus-visible:outline 
                        lg:focus-visible:outline-2 lg:focus-visible:outline-offset-2 
                        lg:focus-visible:outline-gray-600 lg:hidden">Requests</button>
          <!-- Suggestions -->
          <button data-action="click->friendship#toggleSection" data-friendship-target="mobilesuggestionsButton"
            class="col-start-5 col-end-7 rounded-full bg-gray-300 px-1.5 py-2 text-xs font-semibold
                        text-gray-800 shadow-sm lg:hover:bg-gray-500 lg:focus-visible:outline 
                        lg:focus-visible:outline-2 lg:focus-visible:outline-offset-2 
                        lg:focus-visible:outline-gray-600 lg:hidden">Suggestions</button>
        </div>
      </div>
      
        <!-- Pending followers request -->
        <div  id="friend-requests" class="hidden pt-2" data-friendship-target="requestsSection">
          <%= render 'friendships/requests' %>
        </div>  

        <!-- People who are your friends -->
        <div  id="confirmed-friends" class="pt-2" data-friendship-target="friendsSection">
          <%= render 'friendships/confirmed' %>
        </div> 

        <!-- User card for suggested friends -->
        <div  id="suggested-friends" class="hidden pt-2" data-friendship-target="suggestionsSection">
          <%= render 'friendships/suggestions' %>
        </div>  
    </div>       
  </div>        
</div>