config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Devise routes for users
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # Routes for users
  resources :users, only: [:show, :update, :destroy]  

  # Defines the root path route ("/")
  root 'posts#index'

  # Routes for posts
  resources :posts do 
    # Routes for nested routes for likes and comments
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  # Routes for likes
  resources :likes, only: [:create, :destroy]

  # Routes for comments
  resources :comments, only: [:create, :destroy]

  # Routes for friendships
  resources :friendships, only: [:create, :update, :index] do
    member do
      patch :approve
      delete :decline
    end
  end

  # Routes for notifications
  resources :notifications, only: [:index] do
    member do
      post :dismiss
    end
  end

  # Routes for photos
  resources :photos do
    resources :likes, only: [:create]
    resources :comments, only: [:create]
  end

  # Routes for static pages
  get 'market_place', to: 'pages#market_place'
  get 'messenger', to: 'pages#messenger'
  get 'memories', to: 'pages#memories'
  get 'bookmarks', to: 'pages#bookmarks'
  get 'groups', to: 'pages#groups'
  get 'videos', to: 'pages#videos'
end

app/models/post.rb
# frozen_string_literal: true

# Post model to store user posts
class Post < ApplicationRecord
  # Associations
  belongs_to :user
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :photos, dependent: :destroy

end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# Controller for posts
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_post, only: %i[show destroy]
  before_action :check_user, only: [:destroy]

  def index
    if user_signed_in?
      @new_post = Post.new # Initialize a new post for the form
      # Get IDs of approved friends
      friend_ids = current_user.followers.where(friendships: { status: 'approved' }).pluck(:id)

      # Include the current user's ID in the list
      user_ids = friend_ids << current_user.id

      # Fetch posts from current user and approved friends
      @posts = Post.where(user_id: user_ids).order(created_at: :desc)
    else
      redirect_to new_user_registration_path
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      if params[:post][:photo].present?
        if params[:post][:photo].present?
          # Process the uploaded photo and get back a processed file
          processed_file = ImageProcessor.process_and_attach_image(params[:post][:photo], '800x800')
          
          # Build a new photo object and attach the processed image
          photo = @post.photos.build(user: current_user)
          photo.image.attach(io: processed_file, filename: params[:post][:photo].original_filename, content_type: 'image/jpeg')
          photo.save
    
          # Ensure the temporary file is deleted after processing
          processed_file.close
          processed_file.unlink
        end
      end
      Turbo::StreamsChannel.broadcast_refresh_to "post_event"
      redirect_to posts_path, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def show
    @comments = @post.comments.order(created_at: :desc)
  end

  def destroy
    if @post.destroy
      redirect_to posts_path, notice: 'Post was successfully deleted.'
    else
      redirect_to posts_path, alert: 'Unable to delete the post.'
    end
  end

  private

  def post_params
    params.require(:post).permit(:text) # Permit :photo as a parameter
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def check_user
    redirect_to(root_path, alert: 'Unauthorized action.') unless @post.user_id == current_user.id
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

# Helper for post controller
module PostsHelper
end

app/views/posts/_form.html.erb
<!-- Trigger/Open The Modal -->
<div data-controller="modal">
  <div class="container mt-14 justify-center grid grid-rows-2 shadow-md rounded 
              bg-white divide-y-2 divide-gray-200 lg:max-w-20">
      <div class="grid grid-cols-8 bg-white pb-1 pt-2"
            data-action="click->modal#open">
        <!-- Gravatar -->
        <div class="justify-items-end p-2 grid col-start-1 col-end-1"
            data-action="click->modal#open">
          <%= image_tag gravatar_for(current_user), alt: current_user.username, 
                class:"mx-auto h-8 w-auto rounded-full border-2 border-sky-700"
          %>
        </div>
        <!-- Link to create content -->
        <div class="container self-center text-left pr-2 col-start-2 col-end-9 text-gray-900">
          <a href="#" class="block container resize-none p-1 border-2 rounded-lg 
                            py-1.5 text-gray-400 bg-gray-200 placeholder:text-gray-400 
                            focus:ring-0 text-sm sm:leading-6"
              data-action="click->modal#open">
              What are you thinking about <%= current_user.username %>?
          </a>
        </div>
      </div> 
      <!-- Icons -->
      <div class="p-2 self-center grid grid-cols-10">
        <%= render "shared/photo_icon", class:"col-start-1 col-end-1" %>
        <a href="#" class="col-start-2 col-end-4 text-sm text-gray-500"
          data-action="click->modal#open">
          Foto/video
        </a>
      </div>
  </div>

   
  <!-- Create Post Modal -->
  <div id="myModal" class="modal hidden fixed inset-0 z-50 flex items-center justify-center p-4 " 
     data-modal-target="modal"
     data-action="click->modal#closeWithBackgroundClick">
    <!-- Modal Backdrop -->
    <div class="absolute inset-0 bg-gray-500 bg-opacity-75" aria-hidden="true"></div>
    <!-- Modal -->
    <div class="bg-white rounded-lg shadow-xl overflow-hidden w-full max-w-lg mx-auto p-6 space-y-4" data-modal-target="modalContent">
      <div class="px-2 justify-center h-full lg:max-w-20">
        <!-- Post form -->
        <div class=" grid grid-rows-[30px_1px_45px_4fr] h-full shadow-md rounded bg-white bg-white rounded-lg 
                    text-left shadow-xl transform transition-all 
                    sm:max-w-lg sm:w-full">
          <!-- Close Button -->
          <div class="p-2 grid grid-cols-8 row-start-1 row-end-1 h-10">
            <span class="grid self-center justify-center col-start-1 col-end-8 pl-4 text-gray-900 " 
              data-action="click->modal#close">Create Post
            </span>
            <div class="self-center col-start-8 col-end-8 grid justify-end"
                data-action="click->modal#close">
              <%= render 'shared/close_x_icon' %>
            </div>
          </div>
          <!-- Border -->
          <div class="border-solid border-gray-200 border-b row-start-2 row-end-2 h-1"></div>
          <!-- Gravatar -->
          <div class="row-start-3 row-end-3 justify-items-start grid grid-cols-6 p-2 pt-3 ">
            <div class="grid self-center pl-2">
              <%= image_tag gravatar_for(current_user), alt: current_user.username, 
                  class:"mx-auto h-8 w-auto rounded-full col-start-1 col-end-1 border-2 border-sky-700"
              %>
            </div>
            <!-- Username -->
            <div class="text-left pl-1 grid self-center col-start-2 col-end-6"><%= current_user.username %></div>    
          </div>
          <!-- Post text box  -->
          <div class="grid grid-rows-[3.5fr_1fr_1fr] min-w-0 p-3">
            <%= form_with model: @post || Post.new, local: true, html: { multipart: true } do |form| %>
              <div class="h-full rounded-lg shadow-sm">
                <%= form.label :text,"Add your comment", class:"sr-only" %>
                <%= form.text_area :text, class:"h-full container resize-none border-0 
                                                py-1.5 px-2 text-gray-900 bg-gray-200 
                                                placeholder:text-gray-400 rounded-lg 
                                                focus:ring-0 sm:text-sm sm:leading-6", 
                  placeholder:"What are you thinking about, #{current_user.username}?"   
                %>
                <!-- Attach Photo -->
                <div class="grid grid-rows-2 gap-2 py-2">
                  <div class="items-center container ring-1 ring-inset rounded-lg ring-gray-300 
                              focus-within:ring-2 focus-within:ring-sky-600">
                    <div class="grid grid-cols-4 items-center text-xs text-gray-700 p-1">Attach to your post
                      <button type="button" class="h-10 items-center justify-center 
                                                  rounded-full text-gray-400 hover:text-gray-500">
                        <%= form.label :photo do %>
                          <%= form.file_field :photo, class: "hidden" %> 
                          <%= render "shared/paperclip_icon" %>
                        <% end %>
                      </button>
                    </div>
                  </div>
                  <!-- Submit button -->
                  <div class="w-full h-10 items-center rounded-md bg-sky-600 px-3 py-2 text-sm 
                              font-semibold text-white text-center shadow-sm hover:bg-sky-600 
                              focus-visible:outline focus-visible:outline-2 
                              focus-visible:outline-offset-2 focus-visible:outline-sky-600">
                    <%= form.submit "Post" %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_posts_index.html.erb
<%# Index of posts %>
<div class="overflow-auto bg-slate-100 lg:pt-5 lg:min-h-screen lg:bg-slate-100 lg:flex lg:justify-center lg:items-center">
  <div class= "container mx-auto mt-5 justify-center lg:1/2 lg:mx-auto lg:bg-white lg:rounded lg:shadow-md lg:mt-1">
    <ul role="list" class="divide-y divide-gray-100 bg-slate-100 rounded-lg shadow-md">
      <% @posts.each do |post| %> 
        <li data-controller="confirmation", class="py-2 mt-3 bg-white rounded shadow-md"> 
          <div class="grid grid-rows-auto">
            <!-- Avatar and Username -->
            <div class="grid grid-cols-7 items-center">
              <!-- Avatar -->
              <div class="col-start-1 col-end-1 p-3">
                <%= image_tag gravatar_for(post.user), alt: post.user.username, 
                class: "mx-auto h-8 w-auto rounded-full border-2 border-sky-700" %>
              </div>
              <!-- Username and time -->
              <div class="col-start-2 col-end-6">
                <div class="grid grid-rows-1 items-baseline justify-between gap-x-4">
                  <p class="text-sm font-semibold leading-6 text-gray-900"><h3><%= post.user.username %></h3></p>
                  <p class="text-xs text-gray-600">
                    <time datetime="<%= post.created_at %>"><%= time_ago_in_words(post.created_at) %> ago</time>
                  </p>
                </div>
              </div>
              <!-- Delete button for the post -->
              <div class="col-start-7 col-end-7">
                <% if post.user == current_user %>
                  <%= button_to post_path(post), method: :delete, data: { action: "click->confirmation#delete" } do %>
                    <div><%= render 'shared/close_x_icon' %></div>
                  <% end %>
                <% end %>
              </div>
            </div>
            <!-- Post content -->
            <div class="grid grid-cols-7">
              <!-- Post text -->
              <p class="col-start-1 col-end-7 block text-sm text-left resize-none border-0 
                              py-1.5 text-gray-800 items-start overflow-hidden 
                              p-3 ">
                <%= post.text %>  
              </p>
              <!-- Photo -->
              <% if post.photos %>
                <div class="col-start-1 col-end-8 lg:h-1/5">
                  <% post.photos.each do |photo| %>
                    <%= image_tag photo.image, class: "max-w-full h-auto lg:w-full lg:h-auto lg:object-cover" if photo.image.attached? %>
                    <% end %>
                </div>
              <% end %>
              
            </div>
            <!-- Likes Count -->
            <div class="grid grid-cols-9 pt-2">
              <!-- Display the number of likes for the post -->
              <div class="col-start-1 col-end-1 self-center">
                <%= render 'shared/thumbs_up_icon_count' %>
              </div>
              <div class="col-start-2 col-end-3 self-center text-sm text-gray-400">
                <%= post.likes.count %>
              </div>
              
            </div>
            <!-- Border -->
            <div class="border-solid border-gray-200 border-b h-1"></div>
            <!-- Like/Unlike button for the post -->
            <div class="mt-1 text-sm text-gray-400">
              <% if current_user.likes.exists?(likeable: post) %>
                <% like = current_user.likes.find_by(likeable: post) %>
                <%= button_to like_path(like), method: :delete do %>
                  <div class="grid grid-cols-5 self-center">
                    <div><%= render 'shared/thumbs_up_icon' %></div>
                    <span class="self-center">Unlike</span>
                  </div>
                <% end %>
              <% else %>
                <%= button_to likes_path(likeable_id: post.id, likeable_type: 'Post'), method: :post  do %>
                  <div class="ml-1 grid grid-cols-7"> 
                    <div class="col-start-1 col-end-2"><%= render 'shared/thumbs_up_icon' %></div>
                    <span class="ml-1 self-center">Like</span>
                  </div>
                <% end %>
              <% end %>
            </div>
            <!-- Border -->
            <div class="border-solid border-gray-200 border-b h-1"></div>
            <!-- Display existing comments for the post -->
            <div class="comments">
              <!-- Display the most recent comment for the post -->
              <% last_comment = post.comments.order(created_at: :desc).first %>
              <% if last_comment %>
                <div class="grid grid-rows-[10px, 6px] p-1">
                  <div class="grid grid-cols-7 ml-4 ">
                    <div class="col-start-1 col-end-1 p-1 self-center">
                      <%= image_tag gravatar_for(last_comment.user), alt: last_comment.user.username, 
                      class: "mx-auto h-6 w-auto rounded-full border-2 border-sky-700" %>
                    </div>
                    <!-- Display the comment text -->
                    <div class="col-start-2 col-end-7 text-left px-1 pt-1 pl-3
                                text-wrap text-xs bg-gray-100 text-gray-800 
                                border-none resize-none rounded-lg">
                    <%= last_comment.text %>
                    </div> 
                  </div>
                  <%# Like/Unlike button for the comment %>
                  <div class="grid grid-cols-9 self-center">
                    <% comment_like = current_user.likes.find_by(likeable: last_comment) %>
                    <% if comment_like %>
                      <div class="col-start-3 col-end-4">
                        <%= button_to 'Unlike', like_path(comment_like), method: :delete, class:"text-xs text-gray-500" %>
                      </div>
                    <% else %>
                      <div class="col-start-3 col-end-4">
                        <%= button_to likes_path(likeable_id: last_comment.id, likeable_type: 'Comment'), method: :post, class:"text-xs text-gray-500" do %>
                          Like
                        <% end %>
                      </div>
                    <% end %>
                    <div class="col-start-7 col-end-8 self-center ">
                      <%= render 'shared/thumbs_up_icon_count' %>
                    </div>
                    <div class="col-start-8 col-end-9 self-center text-xs text-gray-400 ">
                      <%= last_comment.likes.count %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
            
            <!-- Form to add a new comment -->
            <div class="">  
              <%= form_with(model: Comment.new, url: comments_path, local: true) do |form| %>
                <%= form.hidden_field :commentable_id, value: post.id %>
                <%= form.hidden_field :commentable_type, value: 'Post' %>
                <div class="container mx-auto grid grid-cols-8 pt-2 self-center lg:max-w-32">
                  <% form.label :text %>
                  <div class="cols-start-1 col-end-1 pt-1 pl-3"><%= render 'shared/photo_icon' %></div>
                  <div class="col-start-1 col-end-8 mx-2">
                      <%= form.text_area :text, placeholder: "Write a comment...", class:"w-full h-8 text-xs 
                                                                                  bg-gray-100 border-none 
                                                                                  resize-none rounded-lg
                                                                                  lg:max-w-20" %>
                  </div>
                  <div class="col-start-8 col-end-8 self-center lg:max-w-20">
                    <%= button_tag(type: 'submit', class: "") do %>
                      <%= render 'shared/paperplane_icon' %>
                    <% end %>
                  </div>
                </div>
                
              <% end %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/posts/index.html.erb
<%= turbo_stream_from "post_event" %>
<%= turbo_stream_from "like_event" %>
<%= turbo_stream_from "comment_event" %>
<div class="bg-slate-100">
  <!-- Navbar -->
  <div class="fixed top-0 z-30 w-full">
    <%= render "shared/navbar" %>
  </div>

  <div class="grid grid-cols-1 lg:grid-cols-6 gap-4 pt-3 lg:pt-8">
    <!-- Sidebar -->
    <div class="hidden lg:block lg:col-span-2 lg:pt-8">
      <%= render "shared/sidebar" %>
    </div>

    <!-- Content Area: Form and Posts -->
    <div class="lg:col-span-2 px-4 py-4 ">
    
      <%# New post form %>
      <div class="mb-4 lg:self-center">
        <%= render 'form', new_post: @new_post %>
      </div>
   
      <%# Index of posts %>
      <%= render 'posts/posts_index', posts: @posts %>
    </div>    
  </div>    
</div>